# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 095015279e7b93d2bec3486ffa7da99cf36526a6fcb5cbf28d4dabde1e6599dd0bae0759eb0773bae63d4313091e889c49cac32ad4362f50ecb0da57e4625657

test:
  secret_key_base: 74e73a33038906591bd7e17e718ad303307a42d2f513dab0142bbf03f125ac43f6a9bf2ed19bf70035142b75019bf335c1d46b284978c5cdd93ce3b516055362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
